version: '3.1'

services:
    postgresql:
        image: postgres
        restart: always
        ports:
            - 5432:5432
        environment:
            POSTGRES_PASSWORD: ${PG_PWD}
            POSTGRES_USER: ${PG_USER_FASTAPI}
            POSTGRES_DB: ${PG_DB_NAME}
        volumes:
            - ./pgdata:/var/lib/postgresql/data
            - type: tmpfs
              target: /dev/shm

    pgadmin:
        image: dpage/pgadmin4:latest
        environment:
            PGADMIN_DEFAULT_EMAIL: "admin@admin.com"
            PGADMIN_DEFAULT_PASSWORD: "admin"
        ports:
            - 8080:80
        depends_on:
            - postgresql
